name: Build V3XCTRL deb (arm64)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to build'
        required: false
        default: 'master'

jobs:
  build-arm64-deb:
    name: Build V3XCTRL DEB for ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build in ARM64 Docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfiles/v3xctrl
          platforms: linux/arm64
          push: false
          outputs: type=local,dest=./build/out
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Debug file tree
        run: |
          echo "Listing contents of build/out"
          find build/out

      - name: Upload built .deb package
        uses: actions/upload-artifact@v4
        with:
          name: v3xctrl-arm64
          path: build/out/tmp/*.deb
